default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres

development:
  <<: *default
  database: elochat_development
  host: localhost
  # password: devpassword
  timeout: 5000

test:
  <<: *default
  database: elochat_test
  host: localhost
  min_messages: warning
  # password: testpassword
  timeout: 5000

production:
  <<: *default
  database: elochat_production
  min_messages: error
  pool: 30
  reconnect: true
